sveltejs/learn.svelte.dev

src/lib/client/adapters/webcontainer/index.js
src/routes/tutorial/[slug]/+page.svelte

- add the wait time with the "reset iframe" hack for each time we (re)set the adapter
- listen to server-ready event during reset, because for some reason it's fired then, too. This avoid a race condition where Vite could be requested too early, resulting in a timeout

[fix] make webcontainer integration more robust

---

src/lib/client/adapters/filesystem/index.js
src/lib/client/adapters/webcontainer/index.js
src/lib/types/index.d.ts
src/routes/tutorial/[slug]/+page.svelte
src/routes/tutorial/[slug]/Loading.svelte

- remove steps logic, turns out starting up is very robust if it goes well
- do a full page reload if something fails during initial boot
- make webcontainer a real singleton internally
- use the built-in `rm` method now (works now)
- don't reload iframe if not needed (better DX when solving/resetting)

[fix] webcontainer tweaks

---

content/tutorial/01-svelte/07-lifecycle/01-onmount/README.md

Removes an old reference in the onMount tutorial as the reference has been moved to the advanced section and is no longer before this part.
See: https://learn.svelte.dev/tutorial/onmount (Part 1 / Lifecycle / onMount)
Removed section points to https://learn.svelte.dev/tutorial/bind-this (Part 3 / Advanced bindings / This) as "before"

Remove invalid statement in onMount tutorial

---

src/lib/client/adapters/webcontainer/index.js

fixes a bug wherein resetting an exercise wouldn't delete old directories, upsetting SvelteKit if (for example) a `[colors=hex]` directory was left over without a corresponding `params/hex.js`

delete old directories

---

src/routes/+layout.svelte

This fixes the previously relative link to the discord which didnt work.
Reproduce:
Go to [https://learn.svelte.dev/tutorial/introducing-sveltekit](https://learn.svelte.dev/tutorial/introducing-sveltekit) and click on the discord chat icon in the top right corner.
The link doesnt work.
The browser resolved it to https://learn.svelte.dev/chat which doesnt exist.
I changed it to the absolute link "https://svelte.dev/chat" to make the link work again.

fix relative link to discord

---

src/routes/tutorial/[slug]/Sidebar.svelte

If the content of the sidebar is long enough the users might misclick and choose the *Edit this page* link instead of the *Next: Lesson* link. By doing so, the link will open within the user lesson tab and even if they go back to their previous tab the code progress on that lesson will be lost.
This patch makes the <a> tag on the footer open in a new tab, so if the user misclicks on the link they can close it and continue normally.

fix: <a> tag in footer to open in a new tab

---

content/tutorial/01-svelte/01-introduction/03-dynamic-attributes/README.md

Updated the example to add consistency between the README and the editor experience.

Dynamic Attributes example: make example HTML consistent

---

src/routes/tutorial/[slug]/Editor.svelte

closes #150.
There are basically three ways that the editor could lose focus:
1. the user clicked on the page outside the editor
2. the user tabbed after hitting the `Ctrl-M` or `Ctrl-Shift-M` (on Mac) combo (which temporarily disables focus trapping, I learned today)
3. the iframe captures it
All we need to do, therefore, is determine whether a `focusout` event was caused by 1 or 2, and if so, recapture the focus. It seems to work reliably for me

regain focus when it gets lost by mistake

---

content/tutorial/03-advanced-svelte/04-actions/02-adding-parameters-to-actions/app-a/src/lib/longpress.js
content/tutorial/03-advanced-svelte/04-actions/02-adding-parameters-to-actions/app-b/src/lib/longpress.js

If the component gets destroyed before the timeout is cleared, you'll be invoking a method on a node that should not exist anymore

Clear timeout on destroy

---

content/tutorial/02-sveltekit/04-forms/03-form-validation/README.md

In _Part 2: Introduction to SvelteKit / Forms / Validation_, the code instruction in the left panel lacks a code line.
It's a minor mistake, but it might confuse beginners.

fix: Added missing import 

---

content/tutorial/01-svelte/07-lifecycle/01-onmount/README.md
content/tutorial/01-svelte/07-lifecycle/01-onmount/app-a/src/lib/App.svelte
content/tutorial/01-svelte/07-lifecycle/01-onmount/app-b/src/lib/App.svelte

This PR is about to fix the images for the _Part 1 / Lifecycle / onMount_ excercise
While doing the tutorial, I noticed the images were not loading due to an error of type:
```
GET https://via.placeholder.com/150/61d552 net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep 200
```
By adding:
```
crossorigin="anonymous"
```
To the images, they appear as expected.
I've added the attribute to the initial and the solved state, and removed the warning from the Readme.
Without the attribute:
With the attribute:

[fix] load images in Part 1 / Lifecycle / onMount excercise

---

content/tutorial/02-sveltekit/05-api-routes/01-get-handlers/README.md
content/tutorial/02-sveltekit/05-api-routes/01-get-handlers/app-b/src/routes/roll/+server.js

The tutorial on GET handlers includes a simulation of a dice roll:
`const number = Math.ceil(Math.random() * 6);`
While unlikely, the result of that dice roll might actually be 0. This is because Math.random() returns a number greater than or _equal to 0_.
This PR fixes that by using the follwoing code for the dice roll:
`const number = Math.floor(Math.random() * 6) + 1;`
----
Otherwise thanks for the great tutorial and congrats on the release of SvelteKit!

[fix] dice calculation in "GET handlers"

---

content/tutorial/02-sveltekit/04-forms/02-named-form-actions/README.md

Highlighting the comma in the Task's readme to avoid simple error when copy-pasting.

[fix] highlight 04-forms / 02-named-form-actions

---

content/tutorial/01-svelte/08-stores/06-store-bindings/README.md

- Quotation marks not necessary for code to compile
- The solution code does not use those quotation marks
- Creating strings inside of the quotation marks is uncomfortable

Remove unnecessary and inconsistent quotation marks

---

content/tutorial/01-svelte/07-lifecycle/01-onmount/README.md
content/tutorial/01-svelte/07-lifecycle/01-onmount/app-a/src/lib/App.svelte
content/tutorial/01-svelte/07-lifecycle/01-onmount/app-b/src/lib/App.svelte

Reverts sveltejs/learn.svelte.dev#174

Revert "[fix] load images in Part 1 / Lifecycle / onMount excercise"

---

src/routes/tutorial/[slug]/filetree/File.svelte
src/routes/tutorial/[slug]/state.js

suggestions for #189 — calling `update` and `set` directly feels slightly nicer to me than having a `_state` variable floating around, and creating a new state object seems somehow nicer than mutating the existing one.
also, replaces `editing_state: 'idle' | 'remaining'` with `renaming: boolean`

possible tweaks

---

content/tutorial/common/src/__client.js
package.json
playwright.config.ts
pnpm-lock.yaml
src/routes/tutorial/[slug]/Editor.svelte
tests/focus_management.spec.ts

refs: https://github.com/sveltejs/learn.svelte.dev/pull/190#issuecomment-1405050141, https://github.com/sveltejs/learn.svelte.dev/pull/190#issuecomment-1405322111
typed `export let data;`, but entered `export let dat;`. The `a` is missing.
So, I will create tests to not introduce regressions, and fix this issue.
https://user-images.githubusercontent.com/29677552/214850880-cb09cf60-ab7d-4f74-ade7-a6e2bf25bbd9.mov

fix: typed characters to be entered correctly

---

src/lib/client/adapters/webcontainer/index.js

fix #195 
This is due to `node_modules` being removed when switching tutorials. This only happens when switching from one tutorial with its own `node_modules` to another.
https://github.com/sveltejs/learn.svelte.dev/blob/7f6d1d31486902000965fcdcca9065c38fb9af7b/src/lib/client/adapters/webcontainer/index.js#L141
https://github.com/sveltejs/learn.svelte.dev/blob/7f6d1d31486902000965fcdcca9065c38fb9af7b/src/lib/client/adapters/webcontainer/index.js#L170-L172
This PR is only an ad-hoc fix, but I submit it because I suppose it would be better than the tutorial not working.

fix: not to remove node_modules

---

content/tutorial/01-svelte/06-bindings/05-textarea-inputs/app-a/package.json
content/tutorial/01-svelte/07-lifecycle/03-update/app-a/package.json
scripts/create-common-bundle/unzip.js

fix #178 
This is because the `dev` script is not present in each package.json when running `turbo run dev` in the background.
https://github.com/sveltejs/learn.svelte.dev/blob/7f6d1d31486902000965fcdcca9065c38fb9af7b/src/lib/client/adapters/webcontainer/index.js#L86
The same issue also occurs at https://learn.svelte.dev/tutorial/textarea-inputs, but there is another issue here.
This PR fixes both issues.

fix: add scripts to each package.json

---

content/tutorial/01-svelte/06-bindings/03-checkbox-inputs/app-b/src/lib/App.svelte

Removed redundant whitespaces to make it consistent with `app-a` and docs code style in general

[fix] remove redundant spaces

---

content/tutorial/01-svelte/01-introduction/06-html-tags/README.md

Mainly for the benefit of less experienced programmers that may not be familiar with XSS vulnerabilites, I think replacing the abbreviation and linking to further information would be useful in driving this point home.

Replace XSS abbreviation with Cross-Site Scripting and link to OWASP

---

content/tutorial/02-sveltekit/03-loading-data/02-layout-data/README.md

Paths are missing `routes` folder (`src/blog/...` should instead be `src/routes/blog/...`)

fix: Correct paths in layout-data tutorial

---

vite.config.js

fixes #213 
According to [Vite's documentation](https://vitejs.dev/config/preview-options.html#preview-headers), it seems that it is possible to add headers with the `preview.headers` option, but it doesn't seem to work. I fix it in [this workaround](https://github.com/vitejs/vite/issues/9864#issuecomment-1230560351) (the issue is as of Vite 3, but it is still valid in the current Vite 4).

fix: cross-origin isolation for preview

---

src/lib/client/adapters/webcontainer/index.js
tests/env_file.spec.ts

fixes #206 
There are two problems with #206.
For the first problem, as expected, learn.svelte.dev waits for Vite dev server to restart when a `.dev` file is also added, but Vite only restarts when the `.env` file is changed.
- Vite
https://github.com/vitejs/vite/blob/d953536aae448e2bea0f3a7cb3c0062b16d45597/packages/vite/src/node/server/index.ts#L486-L503
https://github.com/vitejs/vite/blob/d953536aae448e2bea0f3a7cb3c0062b16d45597/packages/vite/src/node/server/hmr.ts#L54-L72
- learn.svelte.dev
https://github.com/sveltejs/learn.svelte.dev/blob/1c3bebf6dd07596924066bf43edd20082700ce08/src/lib/client/adapters/webcontainer/index.js#L235-L243
So, you might assume that just make learn.svelte.dev not wait for Vite dev server to restart when a `.env` file is added, but that would not solve the …

fix: restart Vite if tutorial has a .env file

---

tests/env_file.spec.ts

It seems that CI is failing because one of the tests I added is flaky, sorry.
By setting a longer timeout value for time-consuming tests, this problem can be alleviated.

fix: setTimeout for time-consuming test

---

playwright.config.ts
tests/env_file.spec.ts
tests/focus_management.spec.ts

Sorry to create PRs for tests again and again.
- remove `--enable-features=SharedArrayBuffer` flag (because #214 fixed it)
- set timeout in `playwright.config.ts`
- adjust delay time for flaky tests
The main body of each tests has changed very little.
I ran the tests six times on [GitHub Actions in the folk repository](https://github.com/svelte-jp/learn.svelte.dev/actions/runs/4240086360), and the flaky tests problem seems to have been alleviated.
The `env_file.spec.ts` could be removed once the test passes after [the Vite's issue](https://github.com/vitejs/vite/issues/12127) is fixed. I will submit another PR at that time.

refactor: playwright test

---

content/tutorial/01-svelte/07-lifecycle/02-ondestroy/app-b/src/lib/App.svelte

In `01-svelte/07-lifecycle/02-ondestroy` the boolean `open` switches value from `false` to `true`.
While solving the tutorial, I had to use the "solve" functionality in order to figure out what I was missing. This change of value seems irrelevant to the lesson itself and might bring confusion to others.

Remove irrelevant change from tutorial

---

src/routes/tutorial/[slug]/state.js

Immediately after opening learn.svelte.dev, if you click on the folder, the iframe will reload.
https://user-images.githubusercontent.com/29677552/224252481-a942d749-54c5-4061-98a2-db73268b74dc.mov
Note that I added `expand` to `status` for this fix, but it may not be the proper term (because I couldn't think of a better term with my poor English, sorry...).

fix: prevent iframe from reloading when a folder is clicked

---

src/lib/client/adapters/filesystem/index.js
src/lib/client/adapters/webcontainer/index.js
src/lib/server/content.js
src/lib/types/index.d.ts
src/routes/tutorial/[slug]/+page.svelte
src/routes/tutorial/[slug]/Editor.svelte
src/routes/tutorial/[slug]/Output.svelte
src/routes/tutorial/[slug]/adapter.js
src/routes/tutorial/[slug]/filetree/File.svelte
src/routes/tutorial/[slug]/filetree/Filetree.svelte
src/routes/tutorial/[slug]/filetree/Folder.svelte
src/routes/tutorial/[slug]/filetree/context.js
src/routes/tutorial/[slug]/state.js

This simplifies the adapter code per #248. There was a bit too much indirection previously (also we were conflating state and events, which I think is a bit of a code smell) and I found it quite hard to make changes — there's still room for improvement but I'm much happier with this. 
There are a couple of glitches to work through still:

overhaul adapter code

---

src/routes/tutorial/[slug]/Editor.svelte
src/routes/tutorial/[slug]/state.js

closes #256. feels like there might be a more elegant approach but this will do for now. it's tricky when there are so many ways that the state can be updated

fix solve button

---

content/tutorial/common/src/__client.js
content/tutorial/common/svelte.config.js
package.json
pnpm-lock.yaml
src/routes/tutorial/[slug]/Editor.svelte
src/routes/tutorial/[slug]/Output.svelte
src/routes/tutorial/[slug]/codemirror.css
src/routes/tutorial/[slug]/state.js

show inline diagnostics

---

tests/focus_management.spec.ts

- remove `editor_focus_selector` variable since it is no longer needed
- adjust each timeout
- remove a flaky test case
Perhaps this will improve CI.

chore: refactor test

---

src/routes/tutorial/[slug]/Output.svelte

fix: prevent iframe from flashing when switching tutorial

---

src/routes/tutorial/[slug]/Editor.svelte

a nice side-effect of jettisoning monaco and its overwhelming complexity in favour of codemirror: the editor now works in firefox during dev

firefox now works in dev mode

---

package.json
pnpm-lock.yaml
src/lib/client/adapters/webcontainer/index.js

#266 seems to be caused by a race condition. this appears to fix it

queue all updates

---

src/routes/tutorial/[slug]/Editor.svelte
src/routes/tutorial/[slug]/codemirror.css

this makes the autocomplete dialog look less out of place. it also binds the tab key to `acceptCompletion` which is much more natural

fix autocomplete styles

---

src/routes/tutorial/[slug]/Editor.svelte

Fixes #299 
According to the codemirror documentation, [`setState`](https://codemirror.net/docs/ref/#view.EditorView.setState) reset the view, and may causes some side effects .
Currently `setState` is called every time the code is changed (not just when switching files). It can be fixed by calling it only when switching files

fix: codemirror scroll behaviour

---

scripts/create-common-bundle/index.js
src/lib/server/content.js

The following are logs of a build failed in Vercel (these are from folk site for Japanese, but probably the same error occurs in learn.svelte.dev).
```log
23:29:08.034 | Error: ENOENT: no such file or directory, open 'content/tutorial/01-svelte/06-bindings/05-textarea-inputs/README.md'
23:29:08.034 | at Object.openSync (node:fs:600:3)
23:29:08.034 | at Object.readFileSync (node:fs:468:35)
...
```
This is due to old files still in Vercel.

fix: prevent build failure due to cache files

---

content/tutorial/01-svelte/08-stores/02-auto-subscriptions/README.md

Fixes #314 
This is one of two ways to fix #314.
If #316 will be merged, I will close this PR.

fix: remove link for removed page

---

content/tutorial/01-svelte/07-lifecycle/02-update/app-a/src/lib/App.svelte

User comments appear as empty chat bubbles because we clear the input value _before_ recording the comment string. This fixes that.

Fix user comment bug

---

content/tutorial/01-svelte/04-logic/04-each-blocks/app-a/src/lib/App.svelte
content/tutorial/01-svelte/04-logic/04-each-blocks/app-b/src/lib/App.svelte
content/tutorial/03-advanced-svelte/04-actions/01-actions/README.md
content/tutorial/03-advanced-svelte/04-actions/01-actions/app-a/src/lib/App.svelte
content/tutorial/03-advanced-svelte/04-actions/01-actions/app-a/src/lib/Canvas.svelte
content/tutorial/03-advanced-svelte/04-actions/01-actions/app-a/src/lib/actions.js
content/tutorial/03-advanced-svelte/04-actions/01-actions/app-b/src/lib/App.svelte
content/tutorial/03-advanced-svelte/04-actions/01-actions/app-b/src/lib/actions.js
content/tutorial/common/src/__client.js

This adds a more engaging and understandable exercise for actions.
Unfortunately it reveals a bug — it's currently impossible to complete the exercise, because the iframe keeps snatching the focus. I'm not sure if that's something that broke recently or if this was always broken, but it would be good to fix it if possible.
If not, the workaround would be to not show the menu initially, but that would be sad.

nicer action exercise

---

content/tutorial/02-advanced-svelte/07-composition/05-optional-slots/README.md

one too many sets of curly brackets that throws an error

Too many brackets

---

src/routes/tutorial/[slug]/Editor.svelte

Fixes #324 
The code removed in this PR worked in combination with the processing that was previously in `on:focusout`.
It should no longer be needed now.
As a side note, while I was testing this PR, I learned that Monaco and Codemirror have different tab trapping keys.
https://codemirror.net/examples/tab/

fix: accept autocompletions with Tab key without losing focus

---

content/tutorial/01-svelte/07-lifecycle/01-onmount/README.md

This extra call to the `loop` function isn't present in `app-b/src/lib/App.svelte`, so it should be removed from the text of the tutorial.
I made this commit and PR completely through GitHub, so that's too blame for the change on the last line. I don't know if there's a "newline at EOF" policy for this repository.

Remove extraneous call to loop function

---

package.json
pnpm-lock.yaml
src/routes/+layout.svelte

the tutorial is... basically done? there's still a bunch of issues open but they're non-critical, we can fix them at leisure i think.
similarly, there's some more content we _could_ add, but the tutorial in its current form is pretty comprehensive — certainly comprehensive enough that we should probably start redirecting here from https://svelte.dev/tutorial.
draft because it would be nice to adopt `site-kit@4` (see e.g. https://github.com/sveltejs/site-kit/pull/88)

remove "here be dragons" warning

---

src/routes/tutorial/[slug]/codemirror.css

Fixes #360 
In addition to that, when set to dark-mode in OS and light-mode in learn.svelte.dev (and vice versa), I do not feel the css styles is good enough, so that fixes that as well.
~~I will add more details soon.~~ I added it. please review.

fix: improve styles inside the editor

---

content/tutorial/03-sveltekit/09-errors-and-redirects/02-error-pages/README.md

Already covered in a previous chapter https://learn.svelte.dev/tutorial/page-store

Remove alert about the page store

---

content/tutorial/common/src/__client.js
content/tutorial/common/svelte.config.js
src/lib/client/adapters/webcontainer/index.js
src/routes/tutorial/[slug]/Editor.svelte
src/routes/tutorial/[slug]/Output.svelte
src/routes/tutorial/[slug]/adapter.js
src/routes/tutorial/[slug]/state.js

fix: correct display for warnings

---

src/routes/tutorial/[slug]/Editor.svelte
src/routes/tutorial/[slug]/autocompletion.js
src/routes/tutorial/[slug]/autocompletionDataProvider.js

Fixes part of #291 
- `{#each}`, `{#if}`, `{#await}`, `{#key}`
- `@html`, `@debug`, `@const`
- `data-sveltekit-` attributes
- `on:` directives
- `bind:` directives
autocompletion of import source has not yet been implemented.

feat: autocompletion

---

src/lib/client/adapters/webcontainer/index.js
src/lib/client/adapters/webcontainer/utils.js
src/routes/tutorial/[slug]/Loading.svelte

https://github.com/sveltejs/learn.svelte.dev/issues/306#issuecomment-1542155183
This PR is a temporary workaround, but useful for Safari users.
If using Safari 16.3 or earlier, you will see the same message as before.

chore: safari support

---

content/tutorial/02-advanced-svelte/10-module-context/01-sharing-code/README.md

Thanks for the wonderful tutorial, very much enjoying working through it and learning Svelte / SvelteKit!
This PR corrects a small typo in the sharing code tutorial, the text references five tracks, when there are in fact [four](https://github.com/tcbegley/learn.svelte.dev/blob/e05aafe4e7bfcb0e4a1f35ab511b9d0b01940929/content/tutorial/02-advanced-svelte/10-module-context/01-sharing-code/app-a/src/lib/tracks.js).
I guess it's kind of an off by one error? 😄

docs: Typo in Sharing Code tutorial

---

content/tutorial/01-svelte/05-events/03-event-modifiers/README.md

Migrated from https://github.com/sveltejs/svelte/pull/8715
It looks like the following URL fragment doesn't exist anymore
<https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#Event_bubbling_and_capture>
So while users used to get navigated to the section specifically on bubbling and capture - now they just see the entire Event page.  Which honestly, isn't bad reading, but the event page as a whole is relevant to pretty much every other item in the event modifiers section.  Instead, this inlines links directly to  sections on bubbling vs capture.

docs: fix broken fragment in link

---

content/tutorial/04-advanced-sveltekit/05-advanced-loading/01-universal-load-functions/README.md

Hello!
I noticed that the link located at the bottom of [Universal Load Functions](https://learn.svelte.dev/tutorial/universal-load-functions) points to an outdated section of the documentation. It seems that at some point the title of the section changed making the link also change.

Fixes an outdated link

---

content/tutorial/01-svelte/01-introduction/06-html-tags/README.md

Whenever I have people who a new to web development try the Svelte tutorial, they always freeze at the ominous warning on the @html tag, because they have to wonder "what is HTML that comes from sources I don't trust?".
So I updated the text so it now uses a self authored article as an example of trusted content, and a comment on an article as an example of untrusted content. Hopefully this is a bit more approachable to new developers.

Add examples to @html tag warning

---

README.md
content/tutorial/01-svelte/01-introduction/06-html-tags/README.md

Just a tiny typo fix: `youself` -> `yourself`
Edit: I also found a small typo (`and` -> `an`) in the README after I created the PR and sneaked that inside of this PR, I hope that's okay. 😄

docs: fix typos in @html tag lesson warning and README

---

content/tutorial/01-svelte/02-reactivity/04-updating-arrays-and-objects/app-a/src/lib/App.svelte
content/tutorial/01-svelte/02-reactivity/04-updating-arrays-and-objects/app-b/src/lib/App.svelte

Variable names `t` and `n` would be confusing for beginners, hence changing it to `total` and `currentNumber`

Rename variables for clarity

---

src/routes/tutorial/[slug]/filetree/Item.svelte

I've changed the CSS of the filetree component to make the selected item stand out more from the background color. This helps users see and find the selected item better, especially if they have trouble with colors or vision.

Improve style of selected item in filetree

---

content/tutorial/01-svelte/06-bindings/03-checkbox-inputs/README.md

the actual code is also with double quotes: https://learn.svelte.dev/tutorial/checkbox-inputs

docs: add double quotes to type attribute

---

src/routes/tutorial/[slug]/filetree/ContextMenu.svelte

#439 This pull request fixes the issue where the background of the file explorer left click menu is transparent.

fix: make the background opaque

---

content/tutorial/03-sveltekit/08-stores/01-page-store/README.md

Correcting a typo in the tutorial. The "updat**ed**" store [`$app/stores`](https://kit.svelte.dev/docs/modules#$app-stores-updated) was listed as "updat**ing**".

docs: correct name of `updated` from $app/stores

---

src/routes/tutorial/[slug]/Menu.svelte
src/routes/tutorial/[slug]/Sidebar.svelte

This patch fixes the unavailable `--prime` css variable that were being used on two files. After doing some code searches for that color, I didn't find it anywhere on `svelte.learn.dev` or in `site-kit` repo, by it's name I'm confident that `--sk-theme-1` should be it's natural replacement, but I'm available for future changes if requested.
fixes #454 
```css
.modal-contents button {
background-color: var(--sk-theme-1);
}
```
| Before | After |
|--------|-------|
| ![01-before](https://github.com/sveltejs/learn.svelte.dev/assets/43862225/b7204d0e-fa8e-43ec-95d6-0dc9b744ef24) | ![01-after](https://github.com/sveltejs/learn.svelte.dev/assets/43862225/11e1409b-de6c-4601-b32d-f09217811478) |
---
```css
li[aria-current='step']:not(.expanded) > button {
color: var(--sk-theme-1);
}
```
| Before …

fix: unavailable `--prime` css variable

---

content/tutorial/02-advanced-svelte/08-context/01-context-api/README.md

As an alternative, `console.log({ $count })` could also be used, not sure what's best for this example.

Access store value in context example

---

content/tutorial/02-advanced-svelte/06-classes-and-styles/04-component-styles/README.md
content/tutorial/02-advanced-svelte/06-classes-and-styles/04-component-styles/app-a/src/lib/Box.svelte
content/tutorial/02-advanced-svelte/06-classes-and-styles/04-component-styles/app-b/src/lib/Box.svelte

The tutorial on *Component styles* uses `background-color` in the README.md, while the app uses the shorthand `background`. This could be confusing:
1. The text tells us to 
> change `background-color` ...
but actually changes the `background` in `Box.svelte`.
2. The first snippet uses `background-color` to overwrite `background` in `App.svelte`.  
I replaced the shorthand `background` in the app with `background-color` to make it consistent with the tutorial text.

Replace `background` with `background-color` for consistency

---

content/tutorial/03-sveltekit/06-forms/01-the-form-element/README.md

This commit fix sample code in the-form-element tutorial text, which is `01-the-form-element /README.md`, to match the exercise solution, which is `01-the-form-element/app-b/src/routes/+page.svelte`.
In [the-form-element tutorial page](https://learn.svelte.dev/tutorial/the-form-element),
I found that the sample code in the text was not matched the exercise solution as we can see in the following:
Sample code in the text:
```svelte
<h1>Todos</h1>
<form method="POST">
<label>
add a todo:
<input
name="description"
autocomplete="off"
/>
</label>
</form>
{#each data.todos as todo}
```
Exercise solution:
```svelte
<h1>todos</h1>
<form method="POST">
<label>
add a todo:
<input
name="description"
autocomplete="off"
/>
</label>
</form>
<ul class="todos">
{#each data.todos as todo (todo.id)}
``` …

Fix sample code in tutorial text to match the exercise solution

---

svelte.config.js

Update svelte.config.js to suppress the following warning:
> [vite-plugin-svelte] Option "vitePlugin.experimental.inspector" is no longer experimental and has moved to "vitePlugin.inspector". Please update your svelte config.

Remove `experimental` from inspector option

---

content/tutorial/02-advanced-svelte/07-composition/02-named-slots/README.md

~~I think there is such a trivial matter. 
When I opened `<Card>` component file(`Card.svelte`), I got nothing related to `<span slot="telephone">` inside of that file and instead found it inside of `<App>` component!~~
**--- UPDATED (24 Aug 2023) ---**
I misunderstood the meaning of the instruction.
@geoffrich gave me a better approach. So I changed the title and description of this PR

docs: clarify the meaning of content 

---

content/tutorial/01-svelte/08-stores/06-store-bindings/README.md

Edited instruction to 'add button' to 'add event handler', to reflect the true diff in the code. (The button already exists; the highlighted part is the event handler)

docs: edit instruction for Store Bindings

---

content/tutorial/02-advanced-svelte/05-bindings/03-media-elements/README.md

Svelte added support for the `readyState` media element binding in https://github.com/sveltejs/svelte/pull/6843 . While the docs have been updated to include this option, it was missing in the tutorial.

docs: adds missing `readyState` binding

---

content/tutorial/01-svelte/common/src/routes/+error.svelte
content/tutorial/02-advanced-svelte/common/src/routes/+error.svelte
content/tutorial/03-sveltekit/07-api-routes/02-post-handlers/README.md
content/tutorial/03-sveltekit/07-api-routes/03-other-handlers/README.md

Shorter domain, more status code support

Updating status code references

---

content/tutorial/03-sveltekit/04-headers-and-cookies/02-cookies/README.md
content/tutorial/03-sveltekit/04-headers-and-cookies/02-cookies/app-a/src/routes/+page.server.js

make visited a boolean

---

content/tutorial/03-sveltekit/03-loading-data/02-layout-data/README.md

It was not clear which page below the layout inherits the data, because in fact it could be any page.
The confusion can arise from the way the previous sentence was expressed, as **visually**, there is nothing `below` the layout in the project tree.
There are siblings though, like `+page.svelte` but for a Svelte beginner it is **not** immediately obvious that this page also falls `below` (or **under**) the same layout.

docs: change grammar to help reduce confusion

---

content/tutorial/03-sveltekit/06-forms/01-the-form-element/README.md

Since the chapter is called `Loading data`, this changed link is consistent with it.

docs: make loading data link consistent with the chapter title

---

content/tutorial/03-sveltekit/03-loading-data/01-page-data/README.md
content/tutorial/03-sveltekit/06-forms/04-progressive-enhancement/app-b/src/routes/+page.svelte

- In https://learn.svelte.dev/tutorial/progressive-enhancement, the `button:hover` and `.saving` styles are omitted in the solved state, however other tutorials under the same Forms section, the styles are present in both the initial and solved states.
- This PR aims to fix the inconsistency in the said tutorial.

fix inconsistency of CSS styles between initial and solved state in Part 3 / Forms / Progressive enhancement

---

content/tutorial/03-sveltekit/06-forms/03-form-validation/README.md

The readme is missing the line:
```html
<div class="centered">
``` 
as well as the indentation that are present in the code editor solution.
this can cause a slight confusion while following the tutorial

Update README.md to match solution

---

content/tutorial/02-advanced-svelte/07-composition/02-named-slots/app-a/src/lib/paper.svg

in the tutorial excercise 'named slots', the 'paper.svg' has fill="none". The exercise is to build something that looks like a 'business card' on a table it seems, however you cannot see the card, so it looks more like words etched into wood! screenshot : https://prnt.sc/kpg6vljbZT-T

Update paper.svg fill attr

---

content/tutorial/common/src/app.html

Tiny css change in the tutorial (awesome tutorial btw!): fixes bad contrast for input text in dark mode at, e.g., [/numeric-inputs](https://learn.svelte.dev/tutorial/numeric-inputs)
Feel free to close if you prefer to fix this in another way, thought I'd just put this out there.
Current:
With this PR:

Tutorial: Let inputs and textareas follow theme coloring

---

content/tutorial/01-svelte/05-events/06-dom-event-forwarding/app-a/src/lib/App.svelte

When the button is clicked for a second time before the audio playback triggered by the first click is finished, the second click is ignored. Restarting the playback on every click makes the button feel more responsive.
Useful e.g. when the button is clicked very fast, many times in a row.

fix: restart audio playback on repeated button pushes

---

src/routes/tutorial/[slug]/Sidebar.svelte

I thought that "Edit this page" in the sidebar footer could be moved to the left a bit.
So that it would appear more aligned with the content.
_(difference is in a subtle movement to left of "Edit this page" in footer)_
It's probably the smallest contribution I've ever made :D

fix: smaller sidebar footer horizontal padding

---

content/tutorial/01-svelte/02-reactivity/04-updating-arrays-and-objects/README.md

Ensured clarity in the example code by defining the `obj` object. This ensures that readers understand the context and structure of the object being modified in the reactivity example.
Because it is possible to trigger reactivity by referencing `foo.bar` in the template instead of `obj.foo.bar`, the following will trigger reactivity:
```html
<script>
let obj = { foo: { bar: 'old' } };
const foo = obj.foo;
function updateFooBar() {
foo.bar = 'baz';
}
</script>
<button on:click={updateFooBar}>Update foobar</button>
<p>baz is: {foo.bar}</p>
```
However, the next example will not, and will require `obj = obj` reassignment:
```html
<script>
let obj = { foo: { bar: 'old' } };
const foo = obj.foo;
function updateFooBar() {
foo.bar = 'baz';
// uncomment below to trigger reactivity
// obj = obj 
} …
```

docs: Update README.md

---

content/tutorial/02-advanced-svelte/01-motion/02-springs/app-a/src/lib/App.svelte
content/tutorial/02-advanced-svelte/01-motion/02-springs/app-b/src/lib/App.svelte

Gets rid of this warning:
"presentation" might be better suited here according to ChatGPT: https://chat.openai.com/share/fad5f67a-2f7e-45a4-a759-18e5b9aa44cb
> **presentation:** If the SVG is purely decorative and doesn't convey meaningful content or functionality.
**none:** Similar to **presentation**, used when the SVG doesn't have a direct role for assistive technologies.

add aria-role:none to get rid of warning

---

src/routes/tutorial/[slug]/Sidebar.svelte

This change resolves issue #528 by binding the whole 'section' element to the 'sidebar' variable

fix: sidebar scrolls to top after navigate

---

src/routes/tutorial/[slug]/+page.svelte
src/routes/tutorial/[slug]/Sidebar.svelte

this persists the sidebar scroll state, which IMHO feels a bit more natural when navigating back and forth

persist scroll state

---

tests/env_file.spec.ts

Updated the `env_file` Playwright test to:

fix: env_file playwright tests failing due to animations

---

content/tutorial/03-sveltekit/08-stores/03-updated-store/README.md
content/tutorial/03-sveltekit/08-stores/03-updated-store/app-b/src/routes/+layout.svelte

this is an alternative to #477 — we can't _really_ show `$updated` in action, but we can communicate the gist of it by _starting_ with the toast visible, and then wrapping the toast in `{#if $updated}`. it does a better job than the current version of walking you through it, and gives you something to do

add something to do on updated-store tutorial

---

content/tutorial/03-sveltekit/06-forms/01-the-form-element/app-a/src/routes/+page.server.js
content/tutorial/03-sveltekit/06-forms/01-the-form-element/app-b/src/routes/+page.server.js
content/tutorial/03-sveltekit/06-forms/02-named-form-actions/app-b/src/routes/+page.server.js
content/tutorial/03-sveltekit/06-forms/03-form-validation/app-b/src/routes/+page.server.js
content/tutorial/03-sveltekit/06-forms/05-customizing-use-enhance/app-b/src/routes/+page.server.js

**Lesson**
[The Form Element](https://learn.svelte.dev/tutorial/the-form-element)
**Problem**
In the load function in +page.server.js a new userid is created if not found in cookies
But id is declared as const so it can not be updated
Tutorial app run into 500 internal error
**How to reproduce**
e.g. open link in incognito window
**Fix**
change declaration from id from const to let
Martin
_This is my first open source contribution, so i hope this PR works for you this way_

fix: const to let in "the <form> element"

---

content/tutorial/02-advanced-svelte/07-composition/01-slots/README.md

While going through the [Slots](https://learn.svelte.dev/tutorial/slots) section, I noticed the values of the `div` class were inconsistent.
The text has a space in the value, `<div class="card ">`.
While the `Card.svelte` file didn't have any spaces, `<div class="card">`.

docs: adjust div class value for consistency

---

content/tutorial/02-advanced-svelte/10-module-context/02-module-exports/README.md

In the [module exports](https://learn.svelte.dev/tutorial/module-exports) section, the code snippet in the tutorial content is inconsistent with the source file.

docs: update code snippet for consistency with source file

---

content/tutorial/01-svelte/04-logic/05-keyed-each-blocks/README.md

Try to clarify that it is updating the DOM/components after deleting the last item.
For some reason, I read this as changing the array itself by removing the last item.
I suspect my changes need to be slimmed down and edited.
Yes, I am neuro-divergent. Why do you ask? 😃

Clarify the items in the each needing ids/keys

---

content/tutorial/01-svelte/07-lifecycle/01-onmount/README.md

altho it's generally unimportant, there is missing a semicolon here.

fix: add missing semicolon

---

src/routes/tutorial/[slug]/Loading.svelte
src/routes/tutorial/[slug]/adapter.js

fixes https://github.com/sveltejs/learn.svelte.dev/issues/416
will create a new issue(?) to remind us to remove it when https://github.com/stackblitz/webcontainer-core/issues/1120 is addresed
Prevents user agent strings with `iphone` from loading the webcontainer module. Includes a button in the error message to load the webcontainer anyway in case it's a false positive.
I tested on an iPad mini 4 and it doesn't have the same crashing issue as an iphone hence I omitted it from the user agent string.

fix: prevent iOS from loading webcontainer module

---

src/routes/tutorial/[slug]/filetree/Filetree.svelte
src/routes/tutorial/[slug]/filetree/Item.svelte

I think these warnings are safe to squelch because they fall under 'progressive enhancement'

chore: squelch warnings

---

src/routes/tutorial/[slug]/Menu.svelte

fixes a bug that happens when you try to upgrade to Svelte 5. also, makes the `escape` key close the menu

fix button-inside-button

---

src/lib/client/adapters/webcontainer/index.js
src/lib/types/index.d.ts
src/routes/tutorial/[slug]/adapter.js
src/routes/tutorial/[slug]/state.js

move `CompilerWarning` out of a typedef and into `types.d.ts`, plus some drive-by Prettier fixes

tidy up types

---

package.json
pnpm-lock.yaml
src/lib/types/index.d.ts
src/routes/tutorial/[slug]/filetree/ContextMenu.svelte
src/routes/tutorial/[slug]/filetree/File.svelte
src/routes/tutorial/[slug]/filetree/Filetree.svelte
src/routes/tutorial/[slug]/filetree/Folder.svelte
src/routes/tutorial/[slug]/filetree/Item.svelte

needed to add `prettier-ignore` comments because otherwise it fights with JSDoc. would probably be easier to just use TS, but will save that for the Svelte 5 rewrite

chore: fix type errors

---

package.json
pnpm-lock.yaml
src/routes/+layout.svelte

privacy-compliant way to track performance metrics on our sites

chore: enable Vercel speed insights on site

---

content/tutorial/02-advanced-svelte/07-composition/02-named-slots/app-a/src/lib/App.svelte
content/tutorial/02-advanced-svelte/07-composition/02-named-slots/app-b/src/lib/App.svelte
content/tutorial/02-advanced-svelte/07-composition/03-slot-fallbacks/app-a/src/lib/App.svelte

The slot examples have the ZIP Code on the business card as `100099`, which is too many digits for a ZIP Code and not the one on the card in the film. This PR corrects them to `10099`.

Fix ZIP Code typo in slots examples

---

content/tutorial/02-advanced-svelte/02-transitions/04-custom-css-transitions/README.md

Corrected arrow function syntax to include missing parenthesis around the "t" parameter and added semicolon after the last backtick in returned CSS string. The auto-grader expects both.

Fix spin function syntax for Svelte tutorial

---

content/tutorial/02-advanced-svelte/07-composition/01-slots/app-a/src/lib/paper.svg
content/tutorial/02-advanced-svelte/07-composition/03-slot-fallbacks/app-a/src/lib/paper.svg

as was done in #502  for tutorial exercises 7.02. With `fill="none"`, the business card paper background is not rendered. This PR changes to `fill="white"` in 7.01 and 7.03.
(Really enjoying the tutorial and Svelte in general so far. Thanks for all your work).

Update paper.svg filler for 7.01 & 7.03
