content/tutorial/01-svelte/01-introduction/01-welcome-to-svelte/README.md, content/tutorial/02-sveltekit/01-concepts/01-introducing-sveltekit/README.md, scripts/create-common-bundle/index.js
I've seen some people in the Discord help channels refer to this as the "SvelteKit tutorial", and evidently some YouTube tutorials recommend it. We have the existing "Work in progress" message at the top but I thought this would be more clear that it's not up-to-date.
=> Add advisory about content being out of date

content/tutorial/common/package.json, scripts/create-common-bundle/index.js, src/lib/client/adapters/webcontainer/index.js
This feels a bit messy, but I haven't been able to get stuff to run any other way
=> get vite to run

content/tutorial/01-svelte/common/src/routes/+layout.js, content/tutorial/03-advanced-svelte/common/src/routes/+layout.js
=> [fix] no ssr for Svelte tutorials

package.json, pnpm-lock.yaml, vite.config.js
notably the webcontainer dependency, which hopefully makes things a bit faster/more robust
=> [chore] bump deps

src/lib/types/index.d.ts, src/routes/tutorial/[slug]/+page.svelte, src/routes/tutorial/[slug]/ContextMenu.svelte, src/routes/tutorial/[slug]/File.svelte, src/routes/tutorial/[slug]/Folder.svelte
Not the prettiest, but it works. Allows renaming/editing/adding/removing files. No drag&drop yet.
=> [feat] add context menu

src/routes/tutorial/[slug]/+page.svelte, src/routes/tutorial/[slug]/Editor.svelte
simplifies code and makes it faster, because we don't need to go through Vite
=> [fix] do comparison on input files

src/routes/tutorial/[slug]/+page.svelte
=> opengraph tags and such

src/routes/tutorial/[slug]/+page.svelte
fixes #128. i don't even want to know how
=> fix open-by-default menu

content/tutorial/03-advanced-svelte/10-module-context/01-sharing-code/app-a/src/lib/App.svelte, content/tutorial/03-advanced-svelte/10-module-context/01-sharing-code/app-b/src/lib/App.svelte, content/tutorial/03-advanced-svelte/10-module-context/02-module-exports/app-a/src/lib/App.svelte, content/tutorial/03-advanced-svelte/10-module-context/02-module-exports/app-b/src/lib/App.svelte, src/routes/assets/media/[...path]/+server.js
#125. I'm not sure there's a good way to test this other than to just deploy it, so I guess that's what I'll do
=> proxy assets

content/tutorial/02-sveltekit/02-routing/03-params/README.md, content/tutorial/02-sveltekit/03-loading-data/01-page-data/README.md, content/tutorial/02-sveltekit/03-loading-data/02-layout-data/README.md, content/tutorial/04-advanced-sveltekit/03-advanced-routing/03-param-matchers/README.md, content/tutorial/04-advanced-sveltekit/04-advanced-loading/03-invalidation/README.md, content/tutorial/04-advanced-sveltekit/04-advanced-loading/03-invalidation/app-a/src/routes/+page.js, src/lib/server/content.js, src/lib/types/index.d.ts, src/routes/tutorial/[slug]/+page.svelte, src/routes/tutorial/[slug]/Loading.svelte
=> add a path option to each exercise

src/routes/tutorial/[slug]/+page.svelte
=> preserve URL when resetting

content/tutorial/01-svelte/06-bindings/06-select-bindings/README.md
this could be a prettier / formatting issue? I am not sure if it's the same on all devices and platforms.
=> correct Part 1 / Bindings / Select bindings code line

content/tutorial/common/src/__client.js, src/routes/tutorial/[slug]/Editor.svelte
=> [fix] focus management between editor and iframe

content/tutorial/01-svelte/01-introduction/01-welcome-to-svelte/README.md
response to https://twitter.com/tomaspozo_/status/1615381849131610114
=> clarify 'small'

content/tutorial/02-sveltekit/07-page-options/05-trailingslash/README.md
The position of single quote and back quote was reversed, so I corrected it.
=> [fix] the position of single quote

src/lib/components/filetree/File.svelte
=> [fix] compare with `selected` property for `selected` css

content/tutorial/03-advanced-svelte/03-animations/01-animate/app-a/src/lib/App.svelte
text color updated to black since input box is white, visibility issue fixed
=> Text color updated to black

src/routes/tutorial/[slug]/Menu.svelte
Perhaps this is a typo and I fix it.
=> fix: correct aria-label

src/routes/tutorial/[slug]/Editor.svelte
fixes #164 
ref: https://github.com/microsoft/monaco-editor/issues/648#issuecomment-564978560
=> fix: correct display selected text in editor

content/tutorial/01-svelte/07-lifecycle/03-update/README.md
Note for users on Part 1.7 excersize 3 to go to https://svelte.dev/tutorial/update instead
=> Add note chatbot not working in current excersize

content/tutorial/01-svelte/03-props/03-spread-props/app-a/src/lib/App.svelte, content/tutorial/01-svelte/03-props/03-spread-props/app-b/src/lib/App.svelte
Simple typo correction in tutorial/props/spread-props
=> Use 'blazingly fast' instead of 'blazing fast'

.github/workflows/node.js.yml, playwright.config.ts
=> testing something

src/lib/server/content.js, src/lib/types/index.d.ts, src/routes/tutorial/[slug]/+layout.server.js, src/routes/tutorial/[slug]/Menu.svelte
=> tidy some stuff up

src/routes/tutorial/[slug]/Menu.svelte
=> include all exercises in chapter that matches search

src/routes/tutorial/[slug]/Menu.svelte
=> focus search input when opening menu from header

content/tutorial/01-svelte/07-lifecycle/03-update/README.md
closes #236 — thanks @leothorp
=> remove out of date comment

src/routes/tutorial/[slug]/Sidebar.svelte
=> style links in <code> differently

src/hooks.server.js, src/routes/+page.js, src/routes/assets/media/[...path]/+server.js, src/routes/tutorial/[slug]/+page.server.js, src/routes/tutorial/[slug]/+page.svelte
they're [no longer necessary](https://twitter.com/dummdidumm_/status/1634223835233878016)
=> remove type annotations

package.json, pnpm-lock.yaml, src/routes/+layout.svelte, src/routes/tutorial/[slug]/Editor.svelte
#12. The 'input' screen needs some work
=> mobile layout

package.json, pnpm-lock.yaml, src/routes/tutorial/[slug]/+page.svelte, src/routes/tutorial/[slug]/Editor.svelte, src/routes/tutorial/[slug]/Output.svelte, src/routes/tutorial/[slug]/ScreenToggle.svelte, src/routes/tutorial/[slug]/ToggleButton.svelte, src/routes/tutorial/[slug]/filetree/File.svelte, src/routes/tutorial/[slug]/filetree/Filetree.svelte, src/routes/tutorial/[slug]/filetree/Folder.svelte, src/routes/tutorial/[slug]/filetree/Item.svelte, src/routes/tutorial/[slug]/filetree/context.js
this splits the view in two. TODO: replace the file tree with a pop out menu of some kind
=> better mobile layout

src/routes/tutorial/[slug]/codemirror.css
=> fix cursor styles

src/routes/tutorial/[slug]/Menu.svelte
=> escape strings for regex

src/routes/tutorial/[slug]/codemirror.css
=> chore: reset selection color in editor

src/routes/tutorial/[slug]/+page.svelte
=> fix: correct the order of calling reactive blocks

src/routes/tutorial/[slug]/filetree/Filetree.svelte
https://github.com/sveltejs/learn.svelte.dev/issues/282#issuecomment-1479757899
=> disallow directories being created in place of files and vice versa

src/lib/client/adapters/webcontainer/index.js
=> fix: prevent exercise-specific deps from being deleted

scripts/create-common-bundle/index.js
=> always run clean install

content/tutorial/04-advanced-sveltekit/03-advanced-routing/04-route-groups/README.md, content/tutorial/04-advanced-sveltekit/03-advanced-routing/04-route-groups/app-a/src/routes/login/+page.server.js, content/tutorial/04-advanced-sveltekit/03-advanced-routing/04-route-groups/app-a/src/routes/logout/+page.server.js, content/tutorial/04-advanced-sveltekit/03-advanced-routing/04-route-groups/app-b/src/routes/(authed)/+layout.server.js
Fixes #311 
We need to fix the #314 first. Otherwise build will fail.
=> fix: replace HTTP status code 307 with 303 for redirect

package.json, pnpm-lock.yaml, src/lib/icons/external.svg, src/routes/tutorial/[slug]/+page.svelte, src/routes/tutorial/[slug]/Chrome.svelte, src/routes/tutorial/[slug]/Output.svelte
This completes #329 by adding a new 'open in new tab' icon. It also refactors the component a bit so that more stuff is in CSS
=> open in new tab, part two

content/tutorial/common/src/__client.js, src/routes/tutorial/[slug]/Output.svelte
#335. Unfortunately I think we need to reinstate the `ping` mechanism that was removed in #309. ~~Draft because #309 fixed #298, and this doesn't~~
=> reinstate ping mechanism

svelte.config.js
with this change, we can edit content without breaking everyone's cache
=> practice what we preach

src/lib/client/adapters/webcontainer/index.js
=> preserve newlines

content/tutorial/02-advanced-svelte/07-composition/03-slot-fallbacks/README.md
Small fix for #368 
Changed the filename in the readme.
=> fix filename typo

content/tutorial/04-advanced-sveltekit/01-hooks/04-handleerror/README.md
you way want to -> you may want to
=> Fix typo in handleerror lesson

src/routes/tutorial/[slug]/Sidebar.svelte
Fixes #377 
Left is the current version, right is the fixed version.
=> fix: contrast of diff display in dark mode

content/tutorial/03-sveltekit/06-forms/04-progressive-enhancement/app-b/src/routes/+page.svelte
`<button aria-label='Mark as complete'/>` is missing the style in the solution and delete unused .saving css style.
=> adding a style to button and remove unused css

content/tutorial/common/src/app.html, jsconfig.json, package.json, pnpm-lock.yaml, src/app.html, src/routes/tutorial/[slug]/Output.svelte
This makes the iframe sync up with $theme from site-kit
Updated site-kit to v5
https://user-images.githubusercontent.com/47742487/235906548-99285b43-5462-4336-bb87-624de815515d.mp4
=> feat: User theme aware iframe

content/tutorial/common/src/__client.js
=> fix: handling of a link to redirect URL

content/tutorial/03-sveltekit/05-shared-modules/01-lib/README.md
can be access -> can be accessed
=> Fix typo in SvelteKit $lib lesson

content/tutorial/01-svelte/04-logic/04-each-blocks/README.md
#370 
Updated the example in the tutorial to match the answer in the exercise.
=> Update tutorial [Part 1 / Logic / Each blocks]

content/tutorial/02-advanced-svelte/10-module-context/01-sharing-code/README.md
The goal of this PR is to make it clear that a new script block should be added instead of manipulating the current one.
=> docs: Update text in Sharing code tutorial

content/tutorial/01-svelte/03-props/03-spread-props/app-a/src/lib/App.svelte, content/tutorial/01-svelte/03-props/03-spread-props/app-b/src/lib/App.svelte
=> docs: update Svelte version to 4

content/tutorial/04-advanced-sveltekit/06-environment-variables/01-env-static-private/README.md
Added a missing opening bracket
=> Misplaced Bracket

content/tutorial/01-svelte/04-logic/05-keyed-each-blocks/README.md
The wording provided initially is confusing, and I believe is mistaken.
=> Improved wording.

content/tutorial/04-advanced-sveltekit/04-advanced-routing/04-route-groups/README.md
Component text and slot ordering should match the target app-b: https://github.com/sveltejs/learn.svelte.dev/blob/main/content/tutorial/04-advanced-sveltekit/04-advanced-routing/04-route-groups/app-b/src/routes/(authed)/%2Blayout.svelte
=> Update route-groups doc to match target

content/tutorial/03-sveltekit/06-forms/01-the-form-element/README.md
=> fix incorrect link

content/tutorial/02-advanced-svelte/09-special-elements/09-svelte-options/README.md
Now matches https://svelte.dev/docs/special-elements#svelte-options
=> Update option example for Svelte 4

src/app.css
See this message: https://discord.com/channels/457912077277855764/1163557441741529229
=> Fix diff syntax color in dark mode

content/tutorial/03-sveltekit/08-stores/03-updated-store/README.md
=> docs: minor grammar cleanup in sveltekit tutorial

content/tutorial/01-svelte/05-events/02-inline-handlers/README.md
Match the text in the doc to [the code](https://github.com/sveltejs/learn.svelte.dev/blob/10bdf8d1db67fda81d78f331f2d243d35c494a64/content/tutorial/01-svelte/05-events/02-inline-handlers/app-b/src/lib/App.svelte#L10) in the editor.
=> Update inline handlers doc to sync text

content/tutorial/03-sveltekit/03-loading-data/01-page-data/README.md
=> Update hyphen to emdash for consistency with other list items

content/tutorial/03-sveltekit/06-forms/01-the-form-element/app-a/src/routes/+page.server.js, content/tutorial/03-sveltekit/06-forms/01-the-form-element/app-b/src/routes/+page.server.js, content/tutorial/03-sveltekit/06-forms/02-named-form-actions/app-b/src/routes/+page.server.js, content/tutorial/03-sveltekit/06-forms/03-form-validation/app-b/src/routes/+page.server.js, content/tutorial/03-sveltekit/06-forms/05-customizing-use-enhance/app-b/src/routes/+page.server.js
#508, but fixes adjacent cases too
=> fix form actions chapter
